import numpy as np

URDF_FILENAME = "/robot_data/h1.urdf"

# MOTOR_NAMES = [
#     "HeadYaw",
#     "HeadPitch",
#     "LHipYawPitch",
#     "LHipRoll",
#     "LHipPitch",
#     "LKneePitch",
#     "LAnklePitch",
#     "LAnkleRoll",
#     "RHipYawPitch",
#     "RHipRoll",
#     "RHipPitch",
#     "RKneePitch",
#     "RAnklePitch",
#     "RAnkleRoll",
#     "LShoulderPitch",
#     "LShoulderRoll",
#     "LElbowYaw",
#     "LElbowRoll",
#     "LWristYaw",
#     "LHand",
#     "RShoulderPitch",
#     "RShoulderRoll",
#     "RElbowYaw",
#     "RElbowRoll",
#     "RWristYaw",
#     "RHand"
# ]
SMPL_JOINT_NAMES = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
]

H1_joint_label = [
"left_hip_yaw",
"left_hip_roll",
"left_hip_pitch",
"left_knee",
"left_ankle",
"right_hip_yaw",
"right_hip_roll",
"right_hip_pitch",
"right_knee",
"right_ankle",
"torso",
"left_shoulder_pitch",
"left_shoulder_roll",
"left_shoulder_yaw",
"left_elbow",
"right_shoulder_pitch",
"right_shoulder_roll",
"right_shoulder_yaw",
"right_elbow",
]

